import { Geist, Geist_Mono } from "next/font/google";
import TopBar from "../component/TopBar";
import Footer from "@/component/Footer";
import GoTopButton from "@/component/GoTopButton";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TopBar />
        {children}
        <GoTopButton />
        <Footer />
      </body>
    </html>
  );
}
